apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# v1.4
- github.com/kubeflow/manifests/apps/admission-webhook/upstream/overlays/cert-manager?ref=8478841cd2291ef1fad9e2dc4f4091772a38f197

# Ideally, we shouldn't create an Issuer per component but use a centralized
# Issuer for Kubeflow installation
patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: cert-manager.io/v1
  target:
    group: cert-manager.io
    kind: Certificate
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: cert-manager.io/v1
  target:
    group: cert-manager.io
    kind: Issuer
