apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# v1.4
- github.com/kubeflow/manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=8478841cd2291ef1fad9e2dc4f4091772a38f197

configMapGenerator:
- name: config
  behavior: merge
  literals:
  - ISTIO_GATEWAY=ingress/ingress-gateway
