apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# v1.4
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=8478841cd2291ef1fad9e2dc4f4091772a38f197

configMapGenerator:
- name: config
  behavior: merge
  literals:
  - USERID_HEADER=X-Auth-Request-Email

patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: networking.istio.io/v1beta1
    - op: replace
      path: "/spec/gateways/0"
      value: ingress/ingress-gateway
  target:
    group: networking.istio.io
    kind: VirtualService
